/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.medalfa.saa.querys;

/**
 *
 * @author IngMa
 */
public class kardexQuerys {
////     Obtener kardex de movimientos sin reubicación por clave
//    public static final String OBTENER_KARDEX_POR_CLAVE = "SELECT m.F_IdMov AS noMov, m.F_User AS usuario, IF( m.F_ConMov = 1, com.documento, '') AS documentoCompra, IF ( m.F_ConMov = 1, com.ori, '' ) AS ori, IF ( m.F_ConMov = 1, com.remision, '' ) AS remision, IF ( m.F_ConMov = 1, com.proveedor, '' ) AS proveedor, CASE m.F_ConMov WHEN 51 THEN fact.factura WHEN 3 THEN fact.factura WHEN 1 THEN '' ELSE IFNULL(dev.devolucion,'') END AS folioSalida, CASE m.F_ConMov WHEN 51 THEN fact.unidad WHEN 3 THEN fact.unidad WHEN 1 THEN '' ELSE IFNULL(dev.unidad,'') END AS puntoEntrega, m.F_ConMov, c.F_DesCon AS concepto, m.F_ProMov AS clave, l.F_ClaLot AS lote, DATE_FORMAT( l.F_FecCad, '%%d/%%m/%%Y' ) AS caducidad, ( m.F_CantMov * m.F_SigMov ) AS cantidadMovimiento, u.F_DesUbi AS ubicacion, p.F_DesProy AS proyecto, DATE_FORMAT( m.F_FecMov, '%%d/%%m/%%Y' ) AS fechaMovimiento, m.F_hora AS hora, m.F_LotMov, m.F_UbiMov, m.F_ConMov FROM tb_movinv m INNER JOIN tb_coninv c ON m.F_ConMov = c.F_IdCon INNER JOIN tb_ubica u ON m.F_UbiMov = u.F_ClaUbi INNER JOIN tb_lote l ON m.F_LotMov = l.F_FolLot AND m.F_ProMov = l.F_ClaPro AND m.F_UbiMov = l.F_Ubica LEFT JOIN tb_proyectos p ON l.F_Proyecto = p.F_Id LEFT JOIN ( SELECT c.F_ClaDoc AS documento, c.F_OrdCom AS ori, c.F_FolRemi AS remision, c.F_Lote AS folLot, c.F_ClaPro AS clave, p.F_NomPro AS proveedor FROM tb_compra c INNER JOIN tb_proveedor p ON p.F_ClaProve = c.F_ProVee WHERE c.F_ClaPro = ? GROUP BY c.F_ClaDoc, c.F_FolRemi, c.F_Lote ) com ON com.documento = m.F_DocMov AND com.clave = m.F_ProMov AND com.folLot = m.F_LotMov LEFT JOIN ( SELECT f.F_ClaDoc AS factura, f.F_Lote AS folLot, f.F_ClaPro AS clave, f.F_Proyecto AS proyecto, u.F_NomCli AS unidad FROM tb_factura f INNER JOIN tb_uniatn u ON u.F_ClaCli = f.F_ClaCli AND f.F_ClaPro = ? GROUP BY f.F_ClaDoc, f.F_Proyecto, f.F_Lote ) fact ON fact.factura = m.F_DocMov AND fact.clave = m.F_ProMov AND fact.folLot = m.F_LotMov LEFT JOIN ( SELECT d.F_DocDev AS devolucion, f.F_ClaDoc AS factura, f.F_Lote AS folLot, f.F_ClaPro AS clave, f.F_Proyecto AS proyecto, u.F_NomCli AS unidad FROM tb_factura f INNER JOIN tb_devoluciones d ON f.F_ClaPro = ? AND f.F_ClaDoc = d.F_DocRef INNER JOIN tb_uniatn u ON u.F_ClaCli = f.F_ClaCli GROUP BY f.F_ClaDoc, f.F_Proyecto, f.F_Lote ) dev ON dev.devolucion = m.F_DocMov AND dev.clave = m.F_ProMov AND dev.folLot = m.F_LotMov WHERE m.F_ProMov = ? %s AND m.F_ConMov != 1000 GROUP BY m.F_IdMov ORDER BY m.F_IdMov desc;";
//    // Obtener kardex de movimientos sin reubicación por clave lote y caducidad
//    public static final String OBTENER_KARDEX_POR_LOTE_CADUCIDAD = "SELECT m.F_IdMov AS noMov, m.F_User AS usuario, IF( m.F_ConMov = 1, com.documento, '') AS documentoCompra, IF ( m.F_ConMov = 1, com.ori, '' ) AS ori, IF ( m.F_ConMov = 1, com.remision, '' ) AS remision, IF ( m.F_ConMov = 1, com.proveedor, '' ) AS proveedor, CASE m.F_ConMov WHEN 51 THEN fact.factura WHEN 3 THEN fact.factura WHEN 1 THEN '' ELSE IFNULL(dev.devolucion,'') END AS folioSalida, CASE m.F_ConMov WHEN 51 THEN fact.unidad WHEN 3 THEN fact.unidad WHEN 1 THEN '' ELSE IFNULL(dev.unidad,'') END AS puntoEntrega, m.F_ConMov, c.F_DesCon AS concepto, m.F_ProMov AS clave, l.F_ClaLot AS lote, DATE_FORMAT( l.F_FecCad, '%%d/%%m/%%Y' ) AS caducidad, ( m.F_CantMov * m.F_SigMov ) AS cantidadMovimiento, u.F_DesUbi AS ubicacion, p.F_DesProy AS proyecto, DATE_FORMAT( m.F_FecMov, '%%d/%%m/%%Y' ) AS fechaMovimiento, m.F_hora AS hora, m.F_LotMov, m.F_UbiMov, m.F_ConMov FROM tb_movinv m INNER JOIN tb_coninv c ON m.F_ConMov = c.F_IdCon INNER JOIN tb_ubica u ON m.F_UbiMov = u.F_ClaUbi INNER JOIN tb_lote l ON l.F_ClaLot=? AND l.F_FecCad=? AND l.F_Origen=? AND m.F_LotMov = l.F_FolLot AND m.F_ProMov = l.F_ClaPro AND m.F_UbiMov = l.F_Ubica LEFT JOIN tb_proyectos p ON l.F_Proyecto = p.F_Id LEFT JOIN ( SELECT c.F_ClaDoc AS documento, c.F_OrdCom AS ori, c.F_FolRemi AS remision, c.F_Lote AS folLot, c.F_ClaPro AS clave, p.F_NomPro AS proveedor FROM tb_compra c INNER JOIN tb_proveedor p ON p.F_ClaProve = c.F_ProVee WHERE c.F_ClaPro = ? GROUP BY c.F_ClaDoc, c.F_FolRemi, c.F_Lote ) com ON com.documento = m.F_DocMov AND com.clave = m.F_ProMov AND com.folLot = m.F_LotMov LEFT JOIN ( SELECT f.F_ClaDoc AS factura, f.F_Lote AS folLot, f.F_ClaPro AS clave, f.F_Proyecto AS proyecto, u.F_NomCli AS unidad FROM tb_factura f INNER JOIN tb_uniatn u ON u.F_ClaCli = f.F_ClaCli AND f.F_ClaPro = ? GROUP BY f.F_ClaDoc, f.F_Proyecto, f.F_Lote ) fact ON fact.factura = m.F_DocMov AND fact.clave = m.F_ProMov AND fact.folLot = m.F_LotMov LEFT JOIN ( SELECT d.F_DocDev AS devolucion, f.F_ClaDoc AS factura, f.F_Lote AS folLot, f.F_ClaPro AS clave, f.F_Proyecto AS proyecto, u.F_NomCli AS unidad FROM tb_factura f INNER JOIN tb_devoluciones d ON f.F_ClaPro = ? AND f.F_ClaDoc = d.F_DocRef INNER JOIN tb_uniatn u ON u.F_ClaCli = f.F_ClaCli GROUP BY f.F_ClaDoc, f.F_Proyecto, f.F_Lote ) dev ON dev.devolucion = m.F_DocMov AND dev.clave = m.F_ProMov AND dev.folLot = m.F_LotMov WHERE m.F_ProMov = ? %s AND m.F_ConMov != 1000 GROUP BY m.F_IdMov ORDER BY m.F_IdMov desc;";
//    // Obtener kardex de reubicaciones por claves
//    public static final String OBTENER_KARDEX_REUBICACIONES_POR_CLAVE = "SELECT m.F_User AS usuario, c.F_DesCon AS concepto, m.F_ProMov AS clave, l.F_ClaLot AS lote, DATE_FORMAT( l.F_FecCad, '%%d/%%m/%%Y') AS caducidad,( m.F_CantMov * m.F_SigMov ) AS cantidad, m.F_CostMov AS costo, u.F_DesUbi AS ubicacion, DATE_FORMAT( m.F_FecMov, '%%d/%%m/%%Y' ) AS fechaMovimiento, m.F_hora AS hora, m.F_DocMov AS documento, com.F_FolRemi AS remision, m.F_IdMov AS idMovimiento, l.F_Proyecto AS proyecto, p.F_DesProy AS descProyecto FROM tb_movinv m INNER JOIN tb_coninv c ON m.F_ConMov = c.F_IdCon INNER JOIN tb_ubica u ON m.F_UbiMov = u.F_ClaUbi INNER JOIN tb_lote l ON m.F_LotMov = l.F_FolLot AND m.F_ProMov = l.F_ClaPro AND m.F_UbiMov = l.F_Ubica LEFT JOIN tb_compra com ON l.F_FolLot = com.F_Lote LEFT JOIN tb_proyectos p ON l.F_Proyecto = p.F_Id WHERE m.F_ProMov = ? %s AND ( m.F_ConMov = 1000 OR m.F_ConMov = 1 ) GROUP BY m.F_IdMov ORDER BY m.F_IdMov desc;";
//    public static final String OBTENER_KARDEX_REUBICACIONES_POR_LOTE_Y_CADUCIDAD = "SELECT m.F_User AS usuario, c.F_DesCon AS concepto, m.F_ProMov AS clave, l.F_ClaLot AS lote, DATE_FORMAT( l.F_FecCad, '%%d/%%m/%%Y') AS caducidad,( m.F_CantMov * m.F_SigMov ) AS cantidad, m.F_CostMov AS costo, u.F_DesUbi AS ubicacion, DATE_FORMAT( m.F_FecMov, '%%d/%%m/%%Y' ) AS fechaMovimiento, m.F_hora AS hora, m.F_DocMov AS documento, com.F_FolRemi AS remision, m.F_IdMov AS idMovimiento, l.F_Proyecto AS proyecto, p.F_DesProy AS descProyecto FROM tb_movinv m INNER JOIN tb_coninv c ON m.F_ConMov = c.F_IdCon INNER JOIN tb_ubica u ON m.F_UbiMov = u.F_ClaUbi INNER JOIN tb_lote l ON m.F_LotMov = l.F_FolLot AND m.F_ProMov = l.F_ClaPro AND m.F_UbiMov = l.F_Ubica LEFT JOIN tb_compra com ON l.F_FolLot = com.F_Lote LEFT JOIN tb_proyectos p ON l.F_Proyecto = p.F_Id WHERE m.F_ProMov = ? AND l.F_ClaLot = ? AND l.F_FecCad = ? AND ( m.F_ConMov = 1000 OR m.F_ConMov = 1 ) AND l.F_Origen = ? %s GROUP BY m.F_IdMov ORDER BY m.F_IdMov desc;";
//    // Obtener kardex por fecha 
//    public static final String OBTENER_KARDEX_POR_FECHA = "SELECT m.F_IdMov AS noMov, m.F_ProMov AS claveMovimiento, mm.F_DesPro AS descripcion, m.F_User AS usuario, IF( m.F_ConMov = 1, com.documento, '') AS documentoCompra, IF ( m.F_ConMov = 1, com.ori, '' ) AS ori, IF ( m.F_ConMov = 1, com.remision, '' ) AS remision, IF ( m.F_ConMov = 1, com.proveedor, '' ) AS proveedor, CASE m.F_ConMov WHEN 51 THEN fact.factura WHEN 3 THEN fact.factura WHEN 1 THEN '' ELSE IFNULL( dev.devolucion, '' ) END AS folioSalida, CASE m.F_ConMov WHEN 51 THEN fact.unidad WHEN 3 THEN fact.unidad WHEN 1 THEN '' ELSE IFNULL( dev.unidad, '' ) END AS puntoEntrega, m.F_ConMov, c.F_DesCon AS concepto, m.F_ProMov AS clave, l.F_ClaLot AS lote, DATE_FORMAT( l.F_FecCad, '%d/%m/%Y' ) AS caducidad, ( m.F_CantMov * m.F_SigMov ) AS cantidadMovimiento, u.F_DesUbi AS ubicacion, p.F_DesProy AS proyecto, DATE_FORMAT( m.F_FecMov, '%d/%m/%Y' ) AS fechaMovimiento, m.F_hora AS hora, m.F_LotMov, m.F_UbiMov, m.F_ConMov FROM tb_movinv m INNER JOIN tb_coninv c ON m.F_ConMov = c.F_IdCon INNER JOIN tb_ubica u ON m.F_UbiMov = u.F_ClaUbi INNER JOIN tb_lote l ON m.F_LotMov = l.F_FolLot INNER JOIN tb_medica mm ON mm.F_ClaPro = m.F_ProMov AND m.F_ProMov = l.F_ClaPro AND m.F_UbiMov = l.F_Ubica LEFT JOIN tb_proyectos p ON l.F_Proyecto = p.F_Id LEFT JOIN ( SELECT c.F_ClaDoc AS documento, c.F_OrdCom AS ori, c.F_FolRemi AS remision, c.F_Lote AS folLot, c.F_ClaPro AS clave, p.F_NomPro AS proveedor FROM tb_compra c INNER JOIN tb_proveedor p ON p.F_ClaProve = c.F_ProVee WHERE c.F_FecApl = ? GROUP BY c.F_ClaDoc, c.F_FolRemi, c.F_Lote ) com ON com.documento = m.F_DocMov AND com.clave = m.F_ProMov AND com.folLot = m.F_LotMov LEFT JOIN ( SELECT f.F_ClaDoc AS factura, f.F_Lote AS folLot, f.F_ClaPro AS clave, f.F_Proyecto AS proyecto, u.F_NomCli AS unidad FROM tb_factura f INNER JOIN tb_uniatn u ON u.F_ClaCli = f.F_ClaCli where f.F_FecApl = ? GROUP BY f.F_ClaDoc, f.F_Proyecto, f.F_Lote ) fact ON fact.factura = m.F_DocMov AND fact.clave = m.F_ProMov AND fact.folLot = m.F_LotMov LEFT JOIN ( SELECT d.F_DocDev AS devolucion, f.F_ClaDoc AS factura, f.F_Lote AS folLot, f.F_ClaPro AS clave, f.F_Proyecto AS proyecto, u.F_NomCli AS unidad FROM tb_factura f INNER JOIN tb_devoluciones d ON DATE(d.F_FecDev) = ? AND f.F_ClaDoc = d.F_DocRef INNER JOIN tb_uniatn u ON u.F_ClaCli = f.F_ClaCli GROUP BY f.F_ClaDoc, f.F_Proyecto, f.F_Lote ) dev ON dev.devolucion = m.F_DocMov AND dev.clave = m.F_ProMov AND dev.folLot = m.F_LotMov WHERE m.F_FecMov = ? AND m.F_ConMov != 1000 GROUP BY m.F_IdMov ORDER BY m.F_IdMov desc;";
//    public static final String OBTENER_KARDEX_REDISTRIBUCION_POR_FECHA = "SELECT m.F_User AS usuario, c.F_DesCon AS concepto, m.F_ProMov AS clave, l.F_ClaLot AS lote, DATE_FORMAT( l.F_FecCad, '%d/%m/%Y') AS caducidad,( m.F_CantMov * m.F_SigMov ) AS cantidad, m.F_CostMov AS costo, u.F_DesUbi AS ubicacion, DATE_FORMAT( m.F_FecMov, '%d/%m/%Y' ) AS fechaMovimiento, m.F_hora AS hora, m.F_DocMov AS documento, com.F_FolRemi AS remision, m.F_IdMov AS idMovimiento, l.F_Proyecto AS proyecto, p.F_DesProy AS descProyecto FROM tb_movinv m INNER JOIN tb_coninv c ON m.F_ConMov = c.F_IdCon INNER JOIN tb_ubica u ON m.F_UbiMov = u.F_ClaUbi INNER JOIN tb_lote l ON m.F_LotMov = l.F_FolLot AND m.F_ProMov = l.F_ClaPro AND m.F_UbiMov = l.F_Ubica INNER JOIN tb_compra com ON l.F_FolLot = com.F_Lote LEFT JOIN tb_proyectos p ON l.F_Proyecto = p.F_Id WHERE m.F_FecMov =? AND ( m.F_ConMov = 1000 OR m.F_ConMov = 1 ) GROUP BY m.F_IdMov ORDER BY m.F_IdMov;";
//    public static final String OBTENER_KARDEX_POR_FECHA_EXPORTAR = "SELECT m.F_IdMov AS noMov, m.F_User AS usuario, mm.F_DesPro AS descripcion, IF( m.F_ConMov = 1, com.ori, '') AS ori, IF ( m.F_ConMov = 1, com.remision, '' ) AS remision, IF ( m.F_ConMov = 1, com.proveedor, '' ) AS proveedor, CASE m.F_ConMov WHEN 51 THEN fact.factura WHEN 3 THEN fact.factura WHEN 1 THEN '' ELSE IFNULL( dev.devolucion, '' ) END AS folioSalida, CASE m.F_ConMov WHEN 51 THEN fact.unidad WHEN 3 THEN fact.unidad WHEN 1 THEN '' ELSE IFNULL( dev.unidad, '' ) END AS puntoEntrega, c.F_DesCon AS concepto, m.F_ProMov AS clave, l.F_ClaLot AS lote, DATE_FORMAT( l.F_FecCad, '%d/%m/%Y' ) AS caducidad, ( m.F_CantMov * m.F_SigMov ) AS cantidadMovimiento, u.F_DesUbi AS ubicacion, p.F_DesProy AS proyecto, DATE_FORMAT( m.F_FecMov, '%d/%m/%Y' ) AS fechaMovimiento, m.F_hora AS hora FROM tb_movinv m INNER JOIN tb_coninv c ON m.F_ConMov = c.F_IdCon INNER JOIN tb_ubica u ON m.F_UbiMov = u.F_ClaUbi INNER JOIN tb_lote l ON m.F_LotMov = l.F_FolLot INNER JOIN tb_medica mm ON mm.F_ClaPro = m.F_ProMov AND m.F_ProMov = l.F_ClaPro AND m.F_UbiMov = l.F_Ubica LEFT JOIN tb_proyectos p ON l.F_Proyecto = p.F_Id LEFT JOIN ( SELECT c.F_ClaDoc AS documento, c.F_OrdCom AS ori, c.F_FolRemi AS remision, c.F_Lote AS folLot, c.F_ClaPro AS clave, p.F_NomPro AS proveedor FROM tb_compra c INNER JOIN tb_proveedor p ON p.F_ClaProve = c.F_ProVee WHERE c.F_FecApl = ? GROUP BY c.F_ClaDoc, c.F_FolRemi, c.F_Lote ) com ON com.documento = m.F_DocMov AND com.clave = m.F_ProMov AND com.folLot = m.F_LotMov LEFT JOIN ( SELECT f.F_ClaDoc AS factura, f.F_Lote AS folLot, f.F_ClaPro AS clave, f.F_Proyecto AS proyecto, u.F_NomCli AS unidad FROM tb_factura f INNER JOIN tb_uniatn u ON u.F_ClaCli = f.F_ClaCli AND f.F_FecApl = ? GROUP BY f.F_ClaDoc, f.F_Proyecto, f.F_Lote ) fact ON fact.factura = m.F_DocMov AND fact.clave = m.F_ProMov AND fact.folLot = m.F_LotMov LEFT JOIN ( SELECT d.F_DocDev AS devolucion, f.F_ClaDoc AS factura, f.F_Lote AS folLot, f.F_ClaPro AS clave, f.F_Proyecto AS proyecto, u.F_NomCli AS unidad FROM tb_factura f INNER JOIN tb_devoluciones d ON DATE( d.F_FecDev ) = ? AND f.F_ClaDoc = d.F_DocRef INNER JOIN tb_uniatn u ON u.F_ClaCli = f.F_ClaCli GROUP BY f.F_ClaDoc, f.F_Proyecto, f.F_Lote ) dev ON dev.devolucion = m.F_DocMov AND dev.clave = m.F_ProMov AND dev.folLot = m.F_LotMov WHERE m.F_FecMov = ? AND m.F_ConMov != 1000 GROUP BY m.F_IdMov ORDER BY m.F_IdMov;";
//     
    //    public static final String OBTENER_KARDEX_REDISTRIBUCION_POR_FECHA = "SELECT m.F_User AS usuario, c.F_DesCon AS concepto, m.F_ProMov AS clave, l.F_ClaLot AS lote, DATE_FORMAT( l.F_FecCad, '%d/%m/%Y') AS caducidad,( m.F_CantMov * m.F_SigMov ) AS cantidad, m.F_CostMov AS costo, u.F_DesUbi AS ubicacion, DATE_FORMAT( m.F_FecMov, '%d/%m/%Y' ) AS fechaMovimiento, m.F_hora AS hora, m.F_DocMov AS documento, com.F_FolRemi AS remision, m.F_IdMov AS idMovimiento, l.F_Proyecto AS proyecto, p.F_DesProy AS descProyecto FROM tb_movinv m INNER JOIN tb_coninv c ON m.F_ConMov = c.F_IdCon INNER JOIN tb_ubica u ON m.F_UbiMov = u.F_ClaUbi INNER JOIN tb_lote l ON m.F_LotMov = l.F_FolLot AND m.F_ProMov = l.F_ClaPro AND m.F_UbiMov = l.F_Ubica INNER JOIN tb_compra com ON l.F_FolLot = com.F_Lote LEFT JOIN tb_proyectos p ON l.F_Proyecto = p.F_Id WHERE m.F_FecMov =? AND ( m.F_ConMov = 1000 OR m.F_ConMov = 1 ) GROUP BY m.F_IdMov ORDER BY m.F_IdMov;";
//    public static final String OBTENER_KARDEX_POR_FECHA_EXPORTAR = "SELECT m.F_IdMov AS noMov, m.F_User AS usuario, mm.F_DesPro AS descripcion, IF( m.F_ConMov = 1, com.ori, '') AS ori, IF ( m.F_ConMov = 1, com.remision, '' ) AS remision, IF ( m.F_ConMov = 1, com.proveedor, '' ) AS proveedor, CASE m.F_ConMov WHEN 51 THEN fact.factura WHEN 3 THEN fact.factura WHEN 1 THEN '' ELSE IFNULL( dev.devolucion, '' ) END AS folioSalida, CASE m.F_ConMov WHEN 51 THEN fact.unidad WHEN 3 THEN fact.unidad WHEN 1 THEN '' ELSE IFNULL( dev.unidad, '' ) END AS puntoEntrega, c.F_DesCon AS concepto, m.F_ProMov AS clave, l.F_ClaLot AS lote, DATE_FORMAT( l.F_FecCad, '%d/%m/%Y' ) AS caducidad, ( m.F_CantMov * m.F_SigMov ) AS cantidadMovimiento, u.F_DesUbi AS ubicacion, p.F_DesProy AS proyecto, DATE_FORMAT( m.F_FecMov, '%d/%m/%Y' ) AS fechaMovimiento, m.F_hora AS hora FROM tb_movinv m INNER JOIN tb_coninv c ON m.F_ConMov = c.F_IdCon INNER JOIN tb_ubica u ON m.F_UbiMov = u.F_ClaUbi INNER JOIN tb_lote l ON m.F_LotMov = l.F_FolLot INNER JOIN tb_medica mm ON mm.F_ClaPro = m.F_ProMov AND m.F_ProMov = l.F_ClaPro AND m.F_UbiMov = l.F_Ubica LEFT JOIN tb_proyectos p ON l.F_Proyecto = p.F_Id LEFT JOIN ( SELECT c.F_ClaDoc AS documento, c.F_OrdCom AS ori, c.F_FolRemi AS remision, c.F_Lote AS folLot, c.F_ClaPro AS clave, p.F_NomPro AS proveedor FROM tb_compra c INNER JOIN tb_proveedor p ON p.F_ClaProve = c.F_ProVee WHERE c.F_FecApl = ? GROUP BY c.F_ClaDoc, c.F_FolRemi, c.F_Lote ) com ON com.documento = m.F_DocMov AND com.clave = m.F_ProMov AND com.folLot = m.F_LotMov LEFT JOIN ( SELECT f.F_ClaDoc AS factura, f.F_Lote AS folLot, f.F_ClaPro AS clave, f.F_Proyecto AS proyecto, u.F_NomCli AS unidad FROM tb_factura f INNER JOIN tb_uniatn u ON u.F_ClaCli = f.F_ClaCli AND f.F_FecApl = ? GROUP BY f.F_ClaDoc, f.F_Proyecto, f.F_Lote ) fact ON fact.factura = m.F_DocMov AND fact.clave = m.F_ProMov AND fact.folLot = m.F_LotMov LEFT JOIN ( SELECT d.F_DocDev AS devolucion, f.F_ClaDoc AS factura, f.F_Lote AS folLot, f.F_ClaPro AS clave, f.F_Proyecto AS proyecto, u.F_NomCli AS unidad FROM tb_factura f INNER JOIN tb_devoluciones d ON DATE( d.F_FecDev ) = ? AND f.F_ClaDoc = d.F_DocRef INNER JOIN tb_uniatn u ON u.F_ClaCli = f.F_ClaCli GROUP BY f.F_ClaDoc, f.F_Proyecto, f.F_Lote ) dev ON dev.devolucion = m.F_DocMov AND dev.clave = m.F_ProMov AND dev.folLot = m.F_LotMov WHERE m.F_FecMov = ? AND m.F_ConMov != 1000 GROUP BY m.F_IdMov ORDER BY m.F_IdMov;";
//     
    //  public static final String OBTENER_KARDEX_POR_CLAVE = "SELECT m.F_IdMov AS noMov, m.F_User AS usuario, IF( m.F_ConMov = 1, com.documento, '') AS documentoCompra, IF ( m.F_ConMov = 1, com.ori, '' ) AS ori, IF ( m.F_ConMov = 1, com.remision, '' ) AS remision, IF ( m.F_ConMov = 1, com.proveedor, '' ) AS proveedor, CASE m.F_ConMov WHEN 51 THEN fact.factura WHEN 3 THEN fact.factura WHEN 1 THEN '' ELSE IFNULL(dev.devolucion,'') END AS folioSalida, CASE m.F_ConMov WHEN 51 THEN fact.unidad WHEN 3 THEN fact.unidad WHEN 1 THEN '' ELSE IFNULL(dev.unidad,'') END AS puntoEntrega, m.F_ConMov, c.F_DesCon AS concepto, m.F_ProMov AS clave, l.F_ClaLot AS lote, DATE_FORMAT( l.F_FecCad, '%%d/%%m/%%Y' ) AS caducidad, ( m.F_CantMov * m.F_SigMov ) AS cantidadMovimiento, u.F_DesUbi AS ubicacion, p.F_DesProy AS proyecto, DATE_FORMAT( m.F_FecMov, '%%d/%%m/%%Y' ) AS fechaMovimiento, m.F_hora AS hora, m.F_LotMov, m.F_UbiMov, m.F_ConMov, o.F_DesOri AS origen, IFNULL(m.F_Comentarios,'') AS comentarios FROM tb_movinv m INNER JOIN tb_coninv c ON m.F_ConMov = c.F_IdCon INNER JOIN tb_ubica u ON m.F_UbiMov = u.F_ClaUbi INNER JOIN tb_lote l ON m.F_LotMov = l.F_FolLot AND m.F_ProMov = l.F_ClaPro AND m.F_UbiMov = l.F_Ubica LEFT JOIN tb_proyectos p ON l.F_Proyecto = p.F_Id LEFT JOIN tb_origen o ON o.F_ClaOri = l.F_Origen LEFT JOIN ( SELECT c.F_ClaDoc AS documento, c.F_OrdCom AS ori, c.F_FolRemi AS remision, c.F_Lote AS folLot, c.F_ClaPro AS clave, p.F_NomPro AS proveedor FROM tb_compra c INNER JOIN tb_proveedor p ON p.F_ClaProve = c.F_ProVee WHERE c.F_ClaPro = ? GROUP BY c.F_ClaDoc, c.F_FolRemi, c.F_Lote ) com ON com.documento = m.F_DocMov AND com.clave = m.F_ProMov AND com.folLot = m.F_LotMov LEFT JOIN ( SELECT f.F_ClaDoc AS factura, f.F_Lote AS folLot, f.F_ClaPro AS clave, f.F_Proyecto AS proyecto, u.F_NomCli AS unidad FROM tb_factura f INNER JOIN tb_uniatn u ON u.F_ClaCli = f.F_ClaCli AND f.F_ClaPro = ? GROUP BY f.F_ClaDoc, f.F_Proyecto, f.F_Lote ) fact ON fact.factura = m.F_DocMov AND fact.clave = m.F_ProMov AND fact.folLot = m.F_LotMov LEFT JOIN ( SELECT d.F_DocDev AS devolucion, f.F_ClaDoc AS factura, f.F_Lote AS folLot, f.F_ClaPro AS clave, f.F_Proyecto AS proyecto, u.F_NomCli AS unidad FROM tb_factura f INNER JOIN tb_devoluciones d ON f.F_ClaPro = ? AND f.F_ClaDoc = d.F_DocRef INNER JOIN tb_uniatn u ON u.F_ClaCli = f.F_ClaCli GROUP BY f.F_ClaDoc, f.F_Proyecto, f.F_Lote ) dev ON dev.devolucion = m.F_DocMov AND dev.clave = m.F_ProMov AND dev.folLot = m.F_LotMov WHERE m.F_ProMov = ? %s AND m.F_ConMov NOT IN (1000,1001) GROUP BY m.F_IdMov ORDER BY m.F_IdMov DESC;";
    // Obtener kardex de movimientos sin reubicación por clave lote y caducidad
//    public static final String OBTENER_KARDEX_POR_CLAVE = "SELECT m.F_IdMov AS noMov, m.F_User AS usuario, IF( m.F_ConMov = 1, com.documento, '') AS documentoCompra, IF ( m.F_ConMov = 1, com.ori, '' ) AS ori, IF ( m.F_ConMov = 1, com.remision, '' ) AS remision, IF ( m.F_ConMov = 1, com.proveedor, '' ) AS proveedor, CASE m.F_ConMov WHEN 51 THEN fact.factura WHEN 3 THEN fact.factura WHEN 1 THEN '' ELSE IFNULL(dev.devolucion,'') END AS folioSalida, CASE m.F_ConMov WHEN 51 THEN fact.unidad WHEN 3 THEN fact.unidad WHEN 1 THEN '' ELSE IFNULL(dev.unidad,'') END AS puntoEntrega, m.F_ConMov, c.F_DesCon AS concepto, m.F_ProMov AS clave, l.F_ClaLot AS lote, DATE_FORMAT( l.F_FecCad, '%%d/%%m/%%Y' ) AS caducidad, ( m.F_CantMov * m.F_SigMov ) AS cantidadMovimiento, u.F_DesUbi AS ubicacion, p.F_DesProy AS proyecto, DATE_FORMAT( m.F_FecMov, '%%d/%%m/%%Y' ) AS fechaMovimiento, m.F_hora AS hora, m.F_LotMov, m.F_UbiMov, m.F_ConMov, o.F_DesOri AS origen, IFNULL(m.F_Comentarios,'') AS comentarios FROM tb_movinv m INNER JOIN tb_coninv c ON m.F_ConMov = c.F_IdCon INNER JOIN tb_ubica u ON m.F_UbiMov = u.F_ClaUbi INNER JOIN tb_lote l ON m.F_LotMov = l.F_FolLot AND m.F_ProMov = l.F_ClaPro AND m.F_UbiMov = l.F_Ubica LEFT JOIN tb_proyectos p ON l.F_Proyecto = p.F_Id LEFT JOIN tb_origen o ON o.F_ClaOri = l.F_Origen LEFT JOIN ( SELECT c.F_ClaDoc AS documento, c.F_OrdCom AS ori, c.F_FolRemi AS remision, c.F_Lote AS folLot, c.F_ClaPro AS clave, p.F_NomPro AS proveedor FROM tb_compra c INNER JOIN tb_proveedor p ON p.F_ClaProve = c.F_ProVee WHERE c.F_ClaPro = ? GROUP BY c.F_ClaDoc, c.F_FolRemi, c.F_Lote ) com ON com.documento = m.F_DocMov AND com.clave = m.F_ProMov AND com.folLot = m.F_LotMov LEFT JOIN ( SELECT f.F_ClaDoc AS factura, f.F_Lote AS folLot, f.F_ClaPro AS clave, f.F_Proyecto AS proyecto, u.F_NomCli AS unidad FROM tb_factura f INNER JOIN tb_uniatn u ON u.F_ClaCli = f.F_ClaCli AND f.F_ClaPro = ? GROUP BY f.F_ClaDoc, f.F_Proyecto, f.F_Lote ) fact ON fact.factura = m.F_DocMov AND fact.clave = m.F_ProMov AND fact.folLot = m.F_LotMov LEFT JOIN ( SELECT d.F_DocDev AS devolucion, f.F_ClaDoc AS factura, f.F_Lote AS folLot, f.F_ClaPro AS clave, f.F_Proyecto AS proyecto, u.F_NomCli AS unidad FROM tb_factura f INNER JOIN tb_devoluciones d ON f.F_ClaPro = ? AND f.F_ClaDoc = d.F_DocRef INNER JOIN tb_uniatn u ON u.F_ClaCli = f.F_ClaCli GROUP BY f.F_ClaDoc, f.F_Proyecto, f.F_Lote ) dev ON dev.devolucion = m.F_DocMov AND dev.clave = m.F_ProMov AND dev.folLot = m.F_LotMov WHERE m.F_ProMov = ? %s AND m.F_ConMov NOT IN (1000,1001) GROUP BY m.F_IdMov ORDER BY m.F_IdMov DESC;";

public static final String OBTENER_KARDEX_POR_CLAVE = "SELECT m.F_IdMov AS noMov, IF( m.F_ConMov <> 1, m.F_User, '' ) AS usuario,IF( m.F_ConMov = 1, com.usuariocapt, '' ) AS usuariocapt, IF( m.F_ConMov = 1,  m.F_User, '' ) AS usuariolib, IF( m.F_ConMov = 1, com.documento, '' ) AS documentoCompra, IF( m.F_ConMov = 1, com.ori, '' ) AS ori, IF( m.F_ConMov = 1, com.remision, '' ) AS remision, IF( m.F_ConMov = 1, com.proveedor, '' ) AS proveedor, CASE m.F_ConMov WHEN 51 THEN fact.factura WHEN 3 THEN fact.factura WHEN 4 THEN dev.factura WHEN 5 THEN dev.factura ELSE m.F_DocMov END AS folioSalida, CASE m.F_ConMov WHEN 51 THEN fact.unidad WHEN 3 THEN fact.unidad WHEN 4 THEN dev.unidad WHEN 5 THEN dev.unidad ELSE 'CEDIS CENTRAL' END AS puntoEntrega, m.F_ConMov, c.F_DesCon AS concepto, m.F_ProMov AS clave, l.F_ClaLot AS lote, DATE_FORMAT( l.F_FecCad, '%%d/%%m/%%Y' ) AS caducidad,(m.F_CantMov * m.F_SigMov ) AS cantidadMovimiento, u.F_DesUbi AS ubicacion, p.F_DesProy AS proyecto, DATE_FORMAT( m.F_FecMov, '%%d/%%m/%%Y' ) AS fechaMovimiento, m.F_hora AS hora, m.F_LotMov, m.F_UbiMov, o.F_DesOri AS origen, CASE m.F_ConMov WHEN 1 THEN com.obcom WHEN 3 THEN 'Folio Cancelado' WHEN 4 THEN dev.coment WHEN 5 THEN dev.coment WHEN 51 THEN fact.Comen ELSE '' END AS comentarios,CASE m.F_ConMov WHEN 3 THEN fact.factura WHEN 4 THEN m.F_DocMov WHEN 5 THEN m.F_DocMov ELSE '' END AS folioReferencia,CASE m.F_ConMov WHEN 51 THEN DATE_FORMAT( fact.F_FecEnt, '%%d/%%m/%%Y' ) ELSE '' END AS fechaEnt, CASE WHEN com.ordSuministro = 'NULL' THEN  '' ELSE IFNULL(com.ordSuministro, '') END AS ordSuministro FROM tb_movinv m INNER JOIN tb_coninv c ON m.F_ConMov = c.F_IdCon INNER JOIN tb_ubica u ON m.F_UbiMov = u.F_ClaUbi INNER JOIN tb_lote l ON m.F_LotMov = l.F_FolLot AND m.F_ProMov = l.F_ClaPro AND m.F_UbiMov = l.F_Ubica LEFT JOIN tb_proyectos p ON l.F_Proyecto = p.F_Id LEFT JOIN tb_origen o ON o.F_ClaOri = l.F_Origen \n" +
"LEFT JOIN (SELECT c.F_ClaDoc AS documento,c.F_OrdCom AS ori,c.F_FolRemi AS remision,c.F_Lote AS folLot,c.F_ClaPro AS clave, p.F_NomPro AS proveedor,c.F_Obser AS obcom, c.F_OrdenSuministro AS ordSuministro, c.F_User AS usuariocapt FROM tb_compra c INNER JOIN tb_proveedor p ON p.F_ClaProve = c.F_ProVee WHERE    c.F_ClaPro = ? GROUP BY    c.F_ClaDoc,c.F_FolRemi,c.F_Lote) com ON com.documento = m.F_DocMov AND com.clave = m.F_ProMov AND com.folLot = m.F_LotMov \n" +
"LEFT JOIN (SELECT f.F_ClaDoc AS factura, f.F_Lote AS folLot, f.F_ClaPro AS clave, f.F_Proyecto AS proyecto, u.F_NomCli AS unidad, ob.F_Obser AS Comen,    f.F_FecEnt FROM    tb_factura f INNER JOIN tb_uniatn u ON u.F_ClaCli = f.F_ClaCli  INNER JOIN tb_obserfact ob ON ob.F_IdFact = f.F_ClaDoc AND ob.F_Proyecto = f.F_Proyecto AND f.F_ClaPro = ? GROUP BY f.F_ClaDoc, f.F_Proyecto, f.F_Lote) fact ON fact.factura = m.F_DocMov AND fact.clave = m.F_ProMov AND fact.folLot = m.F_LotMov \n" +
"LEFT JOIN (SELECT d.F_DocDev AS devolucion, d.F_DocRef AS factura, f.F_Lote AS folLot,    f.F_ClaPro AS clave, f.F_Proyecto AS proyecto, u.F_NomCli AS unidad, d.F_Obs AS coment FROM tb_factura f INNER JOIN tb_devoluciones d ON f.F_ClaPro = ? AND f.F_ClaDoc = d.F_DocRef INNER JOIN tb_uniatn u ON u.F_ClaCli = f.F_ClaCli GROUP BY    f.F_ClaDoc, d.F_IdDev, f.F_Proyecto, f.F_Lote) dev ON dev.devolucion = m.F_DocMov AND dev.clave = m.F_ProMov AND dev.folLot = m.F_LotMov WHERE    m.F_ProMov = ? %s AND m.F_ConMov NOT IN ( 1000, 1001 ) GROUP BY    m.F_IdMov ORDER BY m.F_IdMov;";
// Obtener kardex de movimientos sin reubicación por clave lote y caducidad

    public static final String OBTENER_KARDEX_POR_FECHA = "SELECT "
            + "m.F_IdMov AS noMov,"
            + "IF( m.F_ConMov <> 1, m.F_User, '' ) AS usuario, "
            + "IF( m.F_ConMov = 1, com.usuariocapt, '' ) AS usuariocapt, "
            + "IF( m.F_ConMov = 1,  m.F_User, '' ) AS usuariolib,"
            + "IF( m.F_ConMov = 1, com.documento, '' ) AS documentoCompra,"
            + "IF( m.F_ConMov = 1, com.ori, '' ) AS ori,"
            + "IF( m.F_ConMov = 1, com.remision, '' ) AS remision,"
            + "IF( m.F_ConMov = 1, com.proveedor, '' ) AS proveedor,"
            + "IFNULL(CASE m.F_ConMov WHEN 51 THEN fact.factura WHEN 3 THEN fact.factura WHEN 4 THEN dev.factura WHEN 5 THEN dev.factura ELSE m.F_DocMov END,'') AS folioSalida,"
            + "IFNULL(CASE m.F_ConMov WHEN 51 THEN fact.unidad WHEN 3 THEN fact.unidad WHEN 4 THEN dev.unidad WHEN 5 THEN dev.unidad ELSE 'CEDIS CENTRAL' END,'')  AS puntoEntrega,"
            + "c.F_DesCon AS concepto,"
            + "m.F_ProMov AS clave,"
            + "l.F_ClaLot AS lote,"
            + "DATE_FORMAT( l.F_FecCad, '%d/%m/%Y' ) AS caducidad,"
            + "(m.F_CantMov * m.F_SigMov ) AS cantidadMovimiento,"
            + "u.F_DesUbi AS ubicacion,"
            + "o.F_DesOri AS origen,"
            + "p.F_DesProy AS proyecto,"
            + "DATE_FORMAT( m.F_FecMov, '%d/%m/%Y' ) AS fechaMovimiento,"
            + "m.F_hora AS hora,"
            + "IFNULL(CASE m.F_ConMov WHEN 1 THEN com.obcom WHEN 3 THEN 'Folio Cancelado' WHEN 4 THEN dev.coment WHEN 5 THEN dev.coment WHEN 51 THEN fact.Comen ELSE '' END,'') AS comentarios,"
            + "IFNULL(CASE m.F_ConMov WHEN 3 THEN fact.factura WHEN 4 THEN m.F_DocMov WHEN 5 THEN m.F_DocMov ELSE '' END,'') AS folioReferencia,"
            + "IFNULL(CASE m.F_ConMov WHEN 51 THEN DATE_FORMAT( fact.F_FecEnt, '%d/%m/%Y' ) ELSE '' END,'') AS fechaEnt, CASE WHEN com.ordSuministro = 'NULL' THEN  '' ELSE IFNULL(com.ordSuministro, '') END AS ordSuministro "
            + "FROM tb_movinv m "
            + "INNER JOIN tb_coninv c ON m.F_ConMov = c.F_IdCon "
            + "INNER JOIN tb_ubica u ON m.F_UbiMov = u.F_ClaUbi "
            + "INNER JOIN tb_lote l ON m.F_LotMov = l.F_FolLot "
            + "INNER JOIN tb_medica mm ON mm.F_ClaPro = m.F_ProMov AND m.F_ProMov = l.F_ClaPro AND m.F_UbiMov = l.F_Ubica "
            + "LEFT JOIN tb_proyectos p ON l.F_Proyecto = p.F_Id LEFT JOIN tb_origen o ON o.F_ClaOri = l.F_Origen "
            + "LEFT JOIN ("
            + "	SELECT c.F_ClaDoc AS documento,c.F_OrdCom AS ori,c.F_FolRemi AS remision,c.F_Lote AS folLot,c.F_ClaPro AS clave, p.F_NomPro AS proveedor,c.F_Obser AS obcom, c.F_OrdenSuministro AS ordSuministro,c.F_User AS usuariocapt "
            + "	FROM tb_compra c "
            + "	INNER JOIN tb_proveedor p ON p.F_ClaProve = c.F_ProVee "
            + "	WHERE c.F_FecApl = ? "
            + "	GROUP BY c.F_ClaDoc,c.F_FolRemi,c.F_Lote "
            + ") com ON com.documento = m.F_DocMov AND com.clave = m.F_ProMov AND com.folLot = m.F_LotMov "
            + "LEFT JOIN ("
            + "	SELECT f.F_ClaDoc AS factura, f.F_Lote AS folLot, f.F_ClaPro AS clave, f.F_Proyecto AS proyecto, u.F_NomCli AS unidad, ob.F_Obser AS Comen, f.F_FecEnt "
            + "	FROM tb_factura f "
            + "	INNER JOIN tb_uniatn u ON u.F_ClaCli = f.F_ClaCli "
            + "	INNER JOIN tb_obserfact ob ON ob.F_IdFact = f.F_ClaDoc AND ob.F_Proyecto = f.F_Proyecto "
            + "	WHERE f.F_IdFact >= (SELECT f.F_IdFact"
            + "		FROM tb_factura f "
            + "		inner join tb_movinv m ON f.F_ClaDoc = m.F_DocMov AND f.F_ClaPro = m.F_ProMov AND f.F_Lote = m.F_LotMov"
            + "		where  m.F_FecMov = ? AND m.F_ConMov NOT IN ( 1000, 1001 )"
            + "		order by f.F_IdFact asc"
            + "		limit 1)"
            + "	GROUP BY f.F_ClaDoc, f.F_Proyecto, f.F_Lote"
            + ") fact ON fact.factura = m.F_DocMov AND fact.clave = m.F_ProMov AND fact.folLot = m.F_LotMov "
            + "LEFT JOIN ("
            + "	SELECT d.F_DocDev AS devolucion, d.F_DocRef AS factura, f.F_Lote AS folLot, f.F_ClaPro AS clave, f.F_Proyecto AS proyecto, u.F_NomCli AS unidad, d.F_Obs AS coment "
            + "	FROM tb_factura f "
            + "	INNER JOIN tb_devoluciones d ON DATE( d.F_FecDev ) = ? AND f.F_ClaDoc = d.F_DocRef AND f.F_Proyecto = d.F_Proyecto "
            + "	INNER JOIN tb_uniatn u ON u.F_ClaCli = f.F_ClaCli"
            + "	WHERE f.F_IdFact >= (SELECT f.F_IdFact"
            + "		FROM tb_factura f "
            + "		inner join tb_movinv m ON f.F_ClaDoc = m.F_DocMov AND f.F_ClaPro = m.F_ProMov AND f.F_Lote = m.F_LotMov"
            + "		where  m.F_FecMov = ? AND m.F_ConMov NOT IN ( 1000, 1001 )"
            + "		order by f.F_IdFact asc"
            + "		limit 1)"
            + "	GROUP BY f.F_ClaDoc, d.F_IdDev, f.F_Proyecto, f.F_Lote "
            + ") dev ON dev.devolucion = m.F_DocMov AND dev.clave = m.F_ProMov AND dev.folLot = m.F_LotMov "
            + "WHERE m.F_FecMov = ? AND m.F_ConMov NOT IN ( 1000, 1001 )"
            + "GROUP BY m.F_IdMov ORDER BY m.F_IdMov;";
//  public static final String OBTENER_KARDEX_POR_LOTE_CADUCIDAD = "SELECT m.F_IdMov AS noMov, m.F_User AS usuario, IF( m.F_ConMov = 1, com.documento, '') AS documentoCompra, IF ( m.F_ConMov = 1, com.ori, '' ) AS ori, IF ( m.F_ConMov = 1, com.remision, '' ) AS remision, IF ( m.F_ConMov = 1, com.proveedor, '' ) AS proveedor, CASE m.F_ConMov WHEN 51 THEN fact.factura WHEN 3 THEN fact.factura WHEN 1 THEN '' ELSE IFNULL(dev.devolucion,'') END AS folioSalida, CASE m.F_ConMov WHEN 51 THEN fact.unidad WHEN 3 THEN fact.unidad WHEN 1 THEN '' ELSE IFNULL(dev.unidad,'') END AS puntoEntrega, m.F_ConMov, c.F_DesCon AS concepto, m.F_ProMov AS clave, l.F_ClaLot AS lote, DATE_FORMAT( l.F_FecCad, '%%d/%%m/%%Y' ) AS caducidad, ( m.F_CantMov * m.F_SigMov ) AS cantidadMovimiento, u.F_DesUbi AS ubicacion, p.F_DesProy AS proyecto, DATE_FORMAT( m.F_FecMov, '%%d/%%m/%%Y' ) AS fechaMovimiento, m.F_hora AS hora, m.F_LotMov, m.F_UbiMov, m.F_ConMov, o.F_DesOri AS origen, IFNULL(m.F_Comentarios,'') AS comentarios FROM tb_movinv m INNER JOIN tb_coninv c ON m.F_ConMov = c.F_IdCon INNER JOIN tb_ubica u ON m.F_UbiMov = u.F_ClaUbi INNER JOIN tb_lote l ON l.F_ClaLot=? AND l.F_FecCad=? AND l.F_Origen=? AND m.F_LotMov = l.F_FolLot AND m.F_ProMov = l.F_ClaPro AND m.F_UbiMov = l.F_Ubica LEFT JOIN tb_proyectos p ON l.F_Proyecto = p.F_Id LEFT JOIN tb_origen o ON l.F_Origen = o.F_ClaOri LEFT JOIN ( SELECT c.F_ClaDoc AS documento, c.F_OrdCom AS ori, c.F_FolRemi AS remision, c.F_Lote AS folLot, c.F_ClaPro AS clave, p.F_NomPro AS proveedor FROM tb_compra c INNER JOIN tb_proveedor p ON p.F_ClaProve = c.F_ProVee WHERE c.F_ClaPro = ? GROUP BY c.F_ClaDoc, c.F_FolRemi, c.F_Lote ) com ON com.documento = m.F_DocMov AND com.clave = m.F_ProMov AND com.folLot = m.F_LotMov LEFT JOIN ( SELECT f.F_ClaDoc AS factura, f.F_Lote AS folLot, f.F_ClaPro AS clave, f.F_Proyecto AS proyecto, u.F_NomCli AS unidad FROM tb_factura f INNER JOIN tb_uniatn u ON u.F_ClaCli = f.F_ClaCli AND f.F_ClaPro = ? GROUP BY f.F_ClaDoc, f.F_Proyecto, f.F_Lote ) fact ON fact.factura = m.F_DocMov AND fact.clave = m.F_ProMov AND fact.folLot = m.F_LotMov LEFT JOIN ( SELECT d.F_DocDev AS devolucion, f.F_ClaDoc AS factura, f.F_Lote AS folLot, f.F_ClaPro AS clave, f.F_Proyecto AS proyecto, u.F_NomCli AS unidad FROM tb_factura f INNER JOIN tb_devoluciones d ON f.F_ClaPro = ? AND f.F_ClaDoc = d.F_DocRef INNER JOIN tb_uniatn u ON u.F_ClaCli = f.F_ClaCli GROUP BY f.F_ClaDoc, f.F_Proyecto, f.F_Lote ) dev ON dev.devolucion = m.F_DocMov AND dev.clave = m.F_ProMov AND dev.folLot = m.F_LotMov WHERE m.F_ProMov = ? %s AND m.F_ConMov NOT IN (1000,1001) GROUP BY m.F_IdMov ORDER BY m.F_IdMov DESC;";
            // Obtener kardex de reubicaciones por claves
    
    public static final String OBTENER_KARDEX_REUBICACIONES_POR_CLAVE = "SELECT m.F_User AS usuario, c.F_DesCon AS concepto, m.F_ProMov AS clave, l.F_ClaLot AS lote, DATE_FORMAT( l.F_FecCad, '%%d/%%m/%%Y') AS caducidad,( m.F_CantMov * m.F_SigMov ) AS cantidad, m.F_CostMov AS costo, u.F_DesUbi AS ubicacion, DATE_FORMAT( m.F_FecMov, '%%d/%%m/%%Y' ) AS fechaMovimiento, m.F_hora AS hora, m.F_DocMov AS documento, com.F_FolRemi AS remision, m.F_IdMov AS idMovimiento, l.F_Proyecto AS proyecto, p.F_DesProy AS descProyecto, o.F_DesOri AS origen, IFNULL(m.F_Comentarios,'') AS comentarios FROM tb_movinv m INNER JOIN tb_coninv c ON m.F_ConMov = c.F_IdCon INNER JOIN tb_ubica u ON m.F_UbiMov = u.F_ClaUbi INNER JOIN tb_lote l ON m.F_LotMov = l.F_FolLot AND m.F_ProMov = l.F_ClaPro AND m.F_UbiMov = l.F_Ubica LEFT JOIN tb_compra com ON l.F_FolLot = com.F_Lote LEFT JOIN tb_origen o ON l.F_Origen = o.F_ClaOri LEFT JOIN tb_proyectos p ON l.F_Proyecto = p.F_Id WHERE m.F_ProMov = ? %s AND ( m.F_ConMov = 1000 OR m.F_ConMov = 1 OR m.F_ConMov = 1001) GROUP BY m.F_IdMov ORDER BY m.F_IdMov DESC;";
    public static final String OBTENER_KARDEX_REUBICACIONES_POR_LOTE_Y_CADUCIDAD = "SELECT m.F_User AS usuario, c.F_DesCon AS concepto, m.F_ProMov AS clave, l.F_ClaLot AS lote, DATE_FORMAT( l.F_FecCad, '%%d/%%m/%%Y') AS caducidad,( m.F_CantMov * m.F_SigMov ) AS cantidad, m.F_CostMov AS costo, u.F_DesUbi AS ubicacion, DATE_FORMAT( m.F_FecMov, '%%d/%%m/%%Y' ) AS fechaMovimiento, m.F_hora AS hora, m.F_DocMov AS documento, com.F_FolRemi AS remision, m.F_IdMov AS idMovimiento, l.F_Proyecto AS proyecto, p.F_DesProy AS descProyecto, o.F_DesOri AS origen, IFNULL(m.F_Comentarios,'') AS comentarios FROM tb_movinv m INNER JOIN tb_coninv c ON m.F_ConMov = c.F_IdCon INNER JOIN tb_ubica u ON m.F_UbiMov = u.F_ClaUbi INNER JOIN tb_lote l ON m.F_LotMov = l.F_FolLot AND m.F_ProMov = l.F_ClaPro AND m.F_UbiMov = l.F_Ubica LEFT JOIN tb_compra com ON l.F_FolLot = com.F_Lote LEFT JOIN tb_origen o ON o.F_ClaOri = l.F_Origen LEFT JOIN tb_proyectos p ON l.F_Proyecto = p.F_Id WHERE m.F_ProMov = ? AND l.F_ClaLot = ? AND l.F_FecCad = ? AND ( m.F_ConMov = 1000 OR m.F_ConMov = 1 OR m.F_ConMov = 1001 ) AND l.F_Origen = ? %s GROUP BY m.F_IdMov ORDER BY m.F_IdMov DESC;";
    // Obtener kardex por fecha 
//    public static final String OBTENER_KARDEX_POR_LOTE_CADUCIDAD = "SELECT m.F_IdMov AS noMov, m.F_User AS usuario, IF( m.F_ConMov = 1, com.documento, '') AS documentoCompra, IF ( m.F_ConMov = 1, com.ori, '' ) AS ori, IF ( m.F_ConMov = 1, com.remision, '' ) AS remision, IF ( m.F_ConMov = 1, com.proveedor, '' ) AS proveedor, CASE m.F_ConMov WHEN 51 THEN fact.factura WHEN 3 THEN fact.factura WHEN 1 THEN '' ELSE IFNULL(dev.devolucion,'') END AS folioSalida, CASE m.F_ConMov WHEN 51 THEN fact.unidad WHEN 3 THEN fact.unidad WHEN 1 THEN '' ELSE IFNULL(dev.unidad,'') END AS puntoEntrega, m.F_ConMov, c.F_DesCon AS concepto, m.F_ProMov AS clave, l.F_ClaLot AS lote, DATE_FORMAT( l.F_FecCad, '%%d/%%m/%%Y' ) AS caducidad, ( m.F_CantMov * m.F_SigMov ) AS cantidadMovimiento, u.F_DesUbi AS ubicacion, p.F_DesProy AS proyecto, DATE_FORMAT( m.F_FecMov, '%%d/%%m/%%Y' ) AS fechaMovimiento, m.F_hora AS hora, m.F_LotMov, m.F_UbiMov, m.F_ConMov, o.F_DesOri AS origen, IFNULL(m.F_Comentarios,'') AS comentarios FROM tb_movinv m INNER JOIN tb_coninv c ON m.F_ConMov = c.F_IdCon INNER JOIN tb_ubica u ON m.F_UbiMov = u.F_ClaUbi INNER JOIN tb_lote l ON l.F_ClaLot=? AND l.F_FecCad=? AND l.F_Origen=? AND m.F_LotMov = l.F_FolLot AND m.F_ProMov = l.F_ClaPro AND m.F_UbiMov = l.F_Ubica LEFT JOIN tb_proyectos p ON l.F_Proyecto = p.F_Id LEFT JOIN tb_origen o ON l.F_Origen = o.F_ClaOri LEFT JOIN ( SELECT c.F_ClaDoc AS documento, c.F_OrdCom AS ori, c.F_FolRemi AS remision, c.F_Lote AS folLot, c.F_ClaPro AS clave, p.F_NomPro AS proveedor FROM tb_compra c INNER JOIN tb_proveedor p ON p.F_ClaProve = c.F_ProVee WHERE c.F_ClaPro = ? GROUP BY c.F_ClaDoc, c.F_FolRemi, c.F_Lote ) com ON com.documento = m.F_DocMov AND com.clave = m.F_ProMov AND com.folLot = m.F_LotMov LEFT JOIN ( SELECT f.F_ClaDoc AS factura, f.F_Lote AS folLot, f.F_ClaPro AS clave, f.F_Proyecto AS proyecto, u.F_NomCli AS unidad FROM tb_factura f INNER JOIN tb_uniatn u ON u.F_ClaCli = f.F_ClaCli AND f.F_ClaPro = ? GROUP BY f.F_ClaDoc, f.F_Proyecto, f.F_Lote ) fact ON fact.factura = m.F_DocMov AND fact.clave = m.F_ProMov AND fact.folLot = m.F_LotMov LEFT JOIN ( SELECT d.F_DocDev AS devolucion, f.F_ClaDoc AS factura, f.F_Lote AS folLot, f.F_ClaPro AS clave, f.F_Proyecto AS proyecto, u.F_NomCli AS unidad FROM tb_factura f INNER JOIN tb_devoluciones d ON f.F_ClaPro = ? AND f.F_ClaDoc = d.F_DocRef INNER JOIN tb_uniatn u ON u.F_ClaCli = f.F_ClaCli GROUP BY f.F_ClaDoc, f.F_Proyecto, f.F_Lote ) dev ON dev.devolucion = m.F_DocMov AND dev.clave = m.F_ProMov AND dev.folLot = m.F_LotMov WHERE m.F_ProMov = ? %s AND m.F_ConMov NOT IN (1000,1001) GROUP BY m.F_IdMov ORDER BY m.F_IdMov DESC;";
    public static final String OBTENER_KARDEX_POR_LOTE_CADUCIDAD = " SELECT m.F_IdMov AS noMov, IF( m.F_ConMov <> 1, m.F_User, '' ) AS usuario,IF( m.F_ConMov = 1, com.usuariocapt, '' ) AS usuariocapt,IF( m.F_ConMov = 1,  m.F_User, '' ) AS usuariolib, IF( m.F_ConMov = 1, com.documento, '' ) AS documentoCompra, IF( m.F_ConMov = 1, com.ori, '' ) AS ori, IF( m.F_ConMov = 1, com.remision, '' ) AS remision, IF( m.F_ConMov = 1, com.proveedor, '' ) AS proveedor, CASE m.F_ConMov WHEN 51 THEN fact.factura WHEN 3 THEN fact.factura WHEN 4 THEN dev.factura WHEN 5 THEN    dev.factura ELSE m.F_DocMov END AS folioSalida, CASE m.F_ConMov WHEN 51 THEN fact.unidad WHEN 3 THEN fact.unidad WHEN 4 THEN dev.unidad WHEN 5 THEN dev.unidad ELSE 'CEDIS CENTRAL' END AS puntoEntrega, m.F_ConMov, c.F_DesCon AS concepto, m.F_ProMov AS clave, l.F_ClaLot AS lote, DATE_FORMAT( l.F_FecCad, '%%d/%%m/%%Y' ) AS caducidad,(m.F_CantMov * m.F_SigMov ) AS cantidadMovimiento, u.F_DesUbi AS ubicacion, p.F_DesProy AS proyecto, DATE_FORMAT( m.F_FecMov, '%%d/%%m/%%Y' ) AS fechaMovimiento, m.F_hora AS hora, m.F_LotMov, m.F_UbiMov, o.F_DesOri AS origen, CASE m.F_ConMov WHEN 1 THEN com.obcom WHEN 3 THEN 'Folio Cancelado' WHEN 4 THEN dev.coment WHEN 5 THEN dev.coment WHEN 51 THEN fact.Comen ELSE '' END AS comentarios,CASE m.F_ConMov WHEN 3 THEN fact.factura WHEN 4 THEN m.F_DocMov WHEN 5 THEN m.F_DocMov ELSE '' END AS folioReferencia,CASE m.F_ConMov WHEN 51 THEN DATE_FORMAT( fact.F_FecEnt, '%%d/%%m/%%Y' ) ELSE '' END AS fechaEnt, CASE WHEN com.ordSuministro = 'NULL' THEN  '' ELSE IFNULL(com.ordSuministro, '') END AS ordSuministro FROM tb_movinv m "
            + "INNER JOIN tb_coninv c ON m.F_ConMov = c.F_IdCon "
            + "INNER JOIN tb_ubica u ON m.F_UbiMov = u.F_ClaUbi "
            + "INNER JOIN tb_lote l ON l.F_ClaLot=? AND l.F_FecCad=? AND l.F_Origen=? AND m.F_LotMov = l.F_FolLot AND m.F_ProMov = l.F_ClaPro AND m.F_UbiMov = l.F_Ubica "
            + "LEFT JOIN tb_proyectos p ON l.F_Proyecto = p.F_Id LEFT JOIN tb_origen o ON o.F_ClaOri = l.F_Origen \n"
            + " LEFT JOIN (SELECT c.F_ClaDoc AS documento,c.F_OrdCom AS ori,c.F_FolRemi AS remision,c.F_Lote AS folLot,c.F_ClaPro AS clave, p.F_NomPro AS proveedor,c.F_Obser AS obcom, c.F_OrdenSuministro AS ordSuministro, c.F_User AS usuariocapt FROM tb_compra c INNER JOIN tb_proveedor p ON p.F_ClaProve = c.F_ProVee WHERE    c.F_ClaPro = ? GROUP BY    c.F_ClaDoc,c.F_FolRemi,c.F_Lote) com ON com.documento = m.F_DocMov AND com.clave = m.F_ProMov AND com.folLot = m.F_LotMov \n"
            + " LEFT JOIN (SELECT f.F_ClaDoc AS factura, f.F_Lote AS folLot, f.F_ClaPro AS clave, f.F_Proyecto AS proyecto, u.F_NomCli AS unidad, ob.F_Obser AS Comen,    f.F_FecEnt FROM    tb_factura f INNER JOIN tb_uniatn u ON u.F_ClaCli = f.F_ClaCli    INNER JOIN tb_obserfact ob ON ob.F_IdFact = f.F_ClaDoc AND ob.F_Proyecto = f.F_Proyecto   AND f.F_ClaPro = ? GROUP BY f.F_ClaDoc, f.F_Proyecto, f.F_Lote) fact ON fact.factura = m.F_DocMov AND fact.clave = m.F_ProMov AND fact.folLot = m.F_LotMov \n"
            + " LEFT JOIN (SELECT d.F_DocDev AS devolucion, d.F_DocRef AS factura, f.F_Lote AS folLot,    f.F_ClaPro AS clave, f.F_Proyecto AS proyecto, u.F_NomCli AS unidad, d.F_Obs AS coment FROM tb_factura f INNER JOIN tb_devoluciones d ON f.F_ClaPro = ? AND f.F_ClaDoc = d.F_DocRef INNER JOIN tb_uniatn u ON u.F_ClaCli = f.F_ClaCli GROUP BY f.F_ClaDoc, d.F_IdDev, f.F_Proyecto, f.F_Lote) dev ON dev.devolucion = m.F_DocMov  AND dev.clave = m.F_ProMov AND dev.folLot = m.F_LotMov WHERE m.F_ProMov = ? %s AND m.F_ConMov NOT IN ( 1000, 1001 ) GROUP BY    m.F_IdMov ORDER BY m.F_IdMov;";

    // Obtener kardex de reubicaciones por claves
    // public static final String OBTENER_KARDEX_POR_FECHA = "SELECT m.F_IdMov AS noMov, m.F_ProMov AS claveMovimiento, mm.F_DesPro AS descripcion, m.F_User AS usuario, IF( m.F_ConMov = 1, com.documento, '') AS documentoCompra, IF ( m.F_ConMov = 1, com.ori, '' ) AS ori, IF ( m.F_ConMov = 1, com.remision, '' ) AS remision, IF ( m.F_ConMov = 1, com.proveedor, '' ) AS proveedor, CASE m.F_ConMov WHEN 51 THEN fact.factura WHEN 3 THEN fact.factura WHEN 1 THEN '' ELSE IFNULL( dev.devolucion, '' ) END AS folioSalida, CASE m.F_ConMov WHEN 51 THEN fact.unidad WHEN 3 THEN fact.unidad WHEN 1 THEN '' ELSE IFNULL( dev.unidad, '' ) END AS puntoEntrega, m.F_ConMov, c.F_DesCon AS concepto, m.F_ProMov AS clave, l.F_ClaLot AS lote, DATE_FORMAT( l.F_FecCad, '%d/%m/%Y' ) AS caducidad, ( m.F_CantMov * m.F_SigMov ) AS cantidadMovimiento, u.F_DesUbi AS ubicacion, p.F_DesProy AS proyecto, DATE_FORMAT( m.F_FecMov, '%d/%m/%Y' ) AS fechaMovimiento, m.F_hora AS hora, m.F_LotMov, m.F_UbiMov, m.F_ConMov, o.F_DesOri AS origen, IFNULL(m.F_Comentarios,'') as comentarios FROM tb_movinv m INNER JOIN tb_coninv c ON m.F_ConMov = c.F_IdCon INNER JOIN tb_ubica u ON m.F_UbiMov = u.F_ClaUbi INNER JOIN tb_lote l ON m.F_LotMov = l.F_FolLot INNER JOIN tb_medica mm ON mm.F_ClaPro = m.F_ProMov AND m.F_ProMov = l.F_ClaPro AND m.F_UbiMov = l.F_Ubica LEFT JOIN tb_proyectos p ON l.F_Proyecto = p.F_Id  LEFT JOIN tb_origen o ON o.F_ClaOri = l.F_Origen  LEFT JOIN ( SELECT c.F_ClaDoc AS documento, c.F_OrdCom AS ori, c.F_FolRemi AS remision, c.F_Lote AS folLot, c.F_ClaPro AS clave, p.F_NomPro AS proveedor FROM tb_compra c INNER JOIN tb_proveedor p ON p.F_ClaProve = c.F_ProVee WHERE c.F_FecApl = ? GROUP BY c.F_ClaDoc, c.F_FolRemi, c.F_Lote ) com ON com.documento = m.F_DocMov AND com.clave = m.F_ProMov AND com.folLot = m.F_LotMov LEFT JOIN ( SELECT f.F_ClaDoc AS factura, f.F_Lote AS folLot, f.F_ClaPro AS clave, f.F_Proyecto AS proyecto, u.F_NomCli AS unidad FROM tb_factura f INNER JOIN tb_uniatn u ON u.F_ClaCli = f.F_ClaCli WHERE f.F_FecApl = ? GROUP BY f.F_ClaDoc, f.F_Proyecto, f.F_Lote ) fact ON fact.factura = m.F_DocMov AND fact.clave = m.F_ProMov AND fact.folLot = m.F_LotMov LEFT JOIN ( SELECT d.F_DocDev AS devolucion, f.F_ClaDoc AS factura, f.F_Lote AS folLot, f.F_ClaPro AS clave, f.F_Proyecto AS proyecto, u.F_NomCli AS unidad FROM tb_factura f INNER JOIN tb_devoluciones d ON DATE(d.F_FecDev) = ? AND f.F_ClaDoc = d.F_DocRef INNER JOIN tb_uniatn u ON u.F_ClaCli = f.F_ClaCli GROUP BY f.F_ClaDoc, f.F_Proyecto, f.F_Lote ) dev ON dev.devolucion = m.F_DocMov AND dev.clave = m.F_ProMov AND dev.folLot = m.F_LotMov WHERE m.F_FecMov = ? AND m.F_ConMov NOT IN (1000,1001) GROUP BY m.F_IdMov ORDER BY m.F_IdMov DESC;";
    //  public static final String OBTENER_KARDEX_REDISTRIBUCION_POR_FECHA = "SELECT m.F_User AS usuario, c.F_DesCon AS concepto, m.F_ProMov AS clave, l.F_ClaLot AS lote, DATE_FORMAT( l.F_FecCad, '%d/%m/%Y') AS caducidad,( m.F_CantMov * m.F_SigMov ) AS cantidad, m.F_CostMov AS costo, u.F_DesUbi AS ubicacion, DATE_FORMAT( m.F_FecMov, '%d/%m/%Y' ) AS fechaMovimiento, m.F_hora AS hora, m.F_DocMov AS documento, com.F_FolRemi AS remision, m.F_IdMov AS idMovimiento, l.F_Proyecto AS proyecto, p.F_DesProy AS descProyecto, o.F_DesOri AS origen, IFNULL(m.F_Comentarios,'') as comentarios FROM tb_movinv m INNER JOIN tb_coninv c ON m.F_ConMov = c.F_IdCon INNER JOIN tb_ubica u ON m.F_UbiMov = u.F_ClaUbi INNER JOIN tb_lote l ON m.F_LotMov = l.F_FolLot AND m.F_ProMov = l.F_ClaPro AND m.F_UbiMov = l.F_Ubica LEFT JOIN tb_compra com ON l.F_FolLot = com.F_Lote  LEFT JOIN tb_origen o ON o.F_ClaOri = l.F_Origen LEFT JOIN tb_proyectos p ON l.F_Proyecto = p.F_Id WHERE m.F_FecMov =? AND ( m.F_ConMov = 1000 OR m.F_ConMov = 1 OR m.F_ConMov = 1001) GROUP BY m.F_IdMov ORDER BY m.F_IdMov DESC;";
    //  public static final String OBTENER_KARDEX_POR_FECHA_EXPORTAR = "SELECT m.F_IdMov AS noMov, m.F_User AS usuario, mm.F_DesPro AS descripcion, IF( m.F_ConMov = 1, com.ori, '') AS ori, IF ( m.F_ConMov = 1, com.remision, '' ) AS remision, IF ( m.F_ConMov = 1, com.proveedor, '' ) AS proveedor, CASE m.F_ConMov WHEN 51 THEN fact.factura WHEN 3 THEN fact.factura WHEN 1 THEN '' ELSE IFNULL( dev.devolucion, '' ) END AS folioSalida, CASE m.F_ConMov WHEN 51 THEN fact.unidad WHEN 3 THEN fact.unidad WHEN 1 THEN '' ELSE IFNULL( dev.unidad, '' ) END AS puntoEntrega, c.F_DesCon AS concepto, m.F_ProMov AS clave, l.F_ClaLot AS lote, DATE_FORMAT( l.F_FecCad, '%d/%m/%Y' ) AS caducidad, ( m.F_CantMov * m.F_SigMov ) AS cantidadMovimiento, u.F_DesUbi AS ubicacion, p.F_DesProy AS proyecto, DATE_FORMAT( m.F_FecMov, '%d/%m/%Y' ) AS fechaMovimiento, m.F_hora AS hora,o.F_DesOri AS origen, IFNULL(m.F_Comentarios,'') as comentarios  FROM tb_movinv m INNER JOIN tb_coninv c ON m.F_ConMov = c.F_IdCon INNER JOIN tb_ubica u ON m.F_UbiMov = u.F_ClaUbi INNER JOIN tb_lote l ON m.F_LotMov = l.F_FolLot INNER JOIN tb_medica mm ON mm.F_ClaPro = m.F_ProMov AND m.F_ProMov = l.F_ClaPro AND m.F_UbiMov = l.F_Ubica LEFT JOIN tb_proyectos p ON l.F_Proyecto = p.F_Id   LEFT JOIN tb_origen o ON o.F_ClaOri = l.F_Origen LEFT JOIN ( SELECT c.F_ClaDoc AS documento, c.F_OrdCom AS ori, c.F_FolRemi AS remision, c.F_Lote AS folLot, c.F_ClaPro AS clave, p.F_NomPro AS proveedor FROM tb_compra c INNER JOIN tb_proveedor p ON p.F_ClaProve = c.F_ProVee WHERE c.F_FecApl = ? GROUP BY c.F_ClaDoc, c.F_FolRemi, c.F_Lote ) com ON com.documento = m.F_DocMov AND com.clave = m.F_ProMov AND com.folLot = m.F_LotMov LEFT JOIN ( SELECT f.F_ClaDoc AS factura, f.F_Lote AS folLot, f.F_ClaPro AS clave, f.F_Proyecto AS proyecto, u.F_NomCli AS unidad FROM tb_factura f INNER JOIN tb_uniatn u ON u.F_ClaCli = f.F_ClaCli AND f.F_FecApl = ? GROUP BY f.F_ClaDoc, f.F_Proyecto, f.F_Lote ) fact ON fact.factura = m.F_DocMov AND fact.clave = m.F_ProMov AND fact.folLot = m.F_LotMov LEFT JOIN ( SELECT d.F_DocDev AS devolucion, f.F_ClaDoc AS factura, f.F_Lote AS folLot, f.F_ClaPro AS clave, f.F_Proyecto AS proyecto, u.F_NomCli AS unidad FROM tb_factura f INNER JOIN tb_devoluciones d ON DATE( d.F_FecDev ) = ? AND f.F_ClaDoc = d.F_DocRef INNER JOIN tb_uniatn u ON u.F_ClaCli = f.F_ClaCli GROUP BY f.F_ClaDoc, f.F_Proyecto, f.F_Lote ) dev ON dev.devolucion = m.F_DocMov AND dev.clave = m.F_ProMov AND dev.folLot = m.F_LotMov WHERE m.F_FecMov = ? AND m.F_ConMov NOT IN (1000,1001) GROUP BY m.F_IdMov ORDER BY m.F_IdMov;";
//    public static final String OBTENER_KARDEX_REUBICACIONES_POR_CLAVE = "SELECT m.F_User AS usuario, c.F_DesCon AS concepto, m.F_ProMov AS clave, l.F_ClaLot AS lote, DATE_FORMAT( l.F_FecCad, '%%d/%%m/%%Y') AS caducidad,( m.F_CantMov * m.F_SigMov ) AS cantidad, m.F_CostMov AS costo, u.F_DesUbi AS ubicacion, DATE_FORMAT( m.F_FecMov, '%%d/%%m/%%Y' ) AS fechaMovimiento, m.F_hora AS hora, m.F_DocMov AS documento, com.F_FolRemi AS remision, m.F_IdMov AS idMovimiento, l.F_Proyecto AS proyecto, p.F_DesProy AS descProyecto, o.F_DesOri AS origen, IFNULL(m.F_Comentarios,'') AS comentarios FROM tb_movinv m INNER JOIN tb_coninv c ON m.F_ConMov = c.F_IdCon INNER JOIN tb_ubica u ON m.F_UbiMov = u.F_ClaUbi INNER JOIN tb_lote l ON m.F_LotMov = l.F_FolLot AND m.F_ProMov = l.F_ClaPro AND m.F_UbiMov = l.F_Ubica LEFT JOIN tb_compra com ON l.F_FolLot = com.F_Lote LEFT JOIN tb_origen o ON l.F_Origen = o.F_ClaOri LEFT JOIN tb_proyectos p ON l.F_Proyecto = p.F_Id WHERE m.F_ProMov = ? %s AND ( m.F_ConMov = 1000 OR m.F_ConMov = 1 OR m.F_ConMov = 1001) GROUP BY m.F_IdMov ORDER BY m.F_IdMov;";
//    public static final String OBTENER_KARDEX_REUBICACIONES_POR_LOTE_Y_CADUCIDAD = "SELECT m.F_User AS usuario, c.F_DesCon AS concepto, m.F_ProMov AS clave, l.F_ClaLot AS lote, DATE_FORMAT( l.F_FecCad, '%%d/%%m/%%Y') AS caducidad,( m.F_CantMov * m.F_SigMov ) AS cantidad, m.F_CostMov AS costo, u.F_DesUbi AS ubicacion, DATE_FORMAT( m.F_FecMov, '%%d/%%m/%%Y' ) AS fechaMovimiento, m.F_hora AS hora, m.F_DocMov AS documento, com.F_FolRemi AS remision, m.F_IdMov AS idMovimiento, l.F_Proyecto AS proyecto, p.F_DesProy AS descProyecto, o.F_DesOri AS origen, IFNULL(m.F_Comentarios,'') AS comentarios FROM tb_movinv m INNER JOIN tb_coninv c ON m.F_ConMov = c.F_IdCon INNER JOIN tb_ubica u ON m.F_UbiMov = u.F_ClaUbi INNER JOIN tb_lote l ON m.F_LotMov = l.F_FolLot AND m.F_ProMov = l.F_ClaPro AND m.F_UbiMov = l.F_Ubica LEFT JOIN tb_compra com ON l.F_FolLot = com.F_Lote LEFT JOIN tb_origen o ON o.F_ClaOri = l.F_Origen LEFT JOIN tb_proyectos p ON l.F_Proyecto = p.F_Id WHERE m.F_ProMov = ? AND l.F_ClaLot = ? AND l.F_FecCad = ? AND ( m.F_ConMov = 1000 OR m.F_ConMov = 1 OR m.F_ConMov = 1001 ) AND l.F_Origen = ? %s GROUP BY m.F_IdMov ORDER BY m.F_IdMov;";
//     
// Obtener kardex por fecha 
//    public static final String OBTENER_KARDEX_POR_FECHA = "SELECT m.F_IdMov AS noMov, m.F_ProMov AS claveMovimiento, mm.F_DesPro AS descripcion,                 m.F_User AS usuario, IF( m.F_ConMov = 1, com.documento, '') AS documentoCompra, IF ( m.F_ConMov = 1, com.ori, '' ) AS ori, IF ( m.F_ConMov = 1, com.remision, '' ) AS remision, IF ( m.F_ConMov = 1, com.proveedor, '' ) AS proveedor, CASE m.F_ConMov WHEN 51 THEN fact.factura WHEN 3 THEN fact.factura WHEN 1 THEN '' ELSE IFNULL( dev.devolucion, '' ) END AS folioSalida, CASE m.F_ConMov WHEN 51 THEN fact.unidad WHEN 3 THEN fact.unidad WHEN 1 THEN '' ELSE IFNULL( dev.unidad, '' ) END AS puntoEntrega, m.F_ConMov, c.F_DesCon AS concepto, m.F_ProMov AS clave, l.F_ClaLot AS lote, DATE_FORMAT( l.F_FecCad, '%d/%m/%Y' ) AS caducidad, ( m.F_CantMov * m.F_SigMov ) AS cantidadMovimiento, u.F_DesUbi AS ubicacion, p.F_DesProy AS proyecto, DATE_FORMAT( m.F_FecMov, '%d/%m/%Y' ) AS fechaMovimiento, m.F_hora AS hora, m.F_LotMov, m.F_UbiMov, m.F_ConMov, o.F_DesOri AS origen, IFNULL(m.F_Comentarios,'') as comentarios FROM tb_movinv m INNER JOIN tb_coninv c ON m.F_ConMov = c.F_IdCon INNER JOIN tb_ubica u ON m.F_UbiMov = u.F_ClaUbi INNER JOIN tb_lote l ON m.F_LotMov = l.F_FolLot INNER JOIN tb_medica mm ON mm.F_ClaPro = m.F_ProMov AND m.F_ProMov = l.F_ClaPro AND m.F_UbiMov = l.F_Ubica LEFT JOIN tb_proyectos p ON l.F_Proyecto = p.F_Id  LEFT JOIN tb_origen o ON o.F_ClaOri = l.F_Origen  LEFT JOIN ( SELECT c.F_ClaDoc AS documento, c.F_OrdCom AS ori, c.F_FolRemi AS remision, c.F_Lote AS folLot, c.F_ClaPro AS clave, p.F_NomPro AS proveedor FROM tb_compra c INNER JOIN tb_proveedor p ON p.F_ClaProve = c.F_ProVee WHERE c.F_FecApl = ? GROUP BY c.F_ClaDoc, c.F_FolRemi, c.F_Lote ) com ON com.documento = m.F_DocMov AND com.clave = m.F_ProMov AND com.folLot = m.F_LotMov LEFT JOIN ( SELECT f.F_ClaDoc AS factura, f.F_Lote AS folLot, f.F_ClaPro AS clave, f.F_Proyecto AS proyecto, u.F_NomCli AS unidad FROM tb_factura f INNER JOIN tb_uniatn u ON u.F_ClaCli = f.F_ClaCli WHERE f.F_FecApl = ? GROUP BY f.F_ClaDoc, f.F_Proyecto, f.F_Lote ) fact ON fact.factura = m.F_DocMov AND fact.clave = m.F_ProMov AND fact.folLot = m.F_LotMov LEFT JOIN ( SELECT d.F_DocDev AS devolucion, f.F_ClaDoc AS factura, f.F_Lote AS folLot, f.F_ClaPro AS clave, f.F_Proyecto AS proyecto, u.F_NomCli AS unidad FROM tb_factura f INNER JOIN tb_devoluciones d ON DATE(d.F_FecDev) = ? AND f.F_ClaDoc = d.F_DocRef INNER JOIN tb_uniatn u ON u.F_ClaCli = f.F_ClaCli GROUP BY f.F_ClaDoc, f.F_Proyecto, f.F_Lote ) dev ON dev.devolucion = m.F_DocMov AND dev.clave = m.F_ProMov AND dev.folLot = m.F_LotMov WHERE m.F_FecMov = ? AND m.F_ConMov NOT IN (1000,1001) GROUP BY m.F_IdMov ORDER BY m.F_IdMov DESC;";
//    public static final String OBTENER_KARDEX_POR_FECHA = "SELECT m.F_IdMov AS noMov, m.F_User AS usuario,  IF( m.F_ConMov = 1, com.documento, '' ) AS documentoCompra, IF( m.F_ConMov = 1, com.ori, '' ) AS ori, IF( m.F_ConMov = 1, com.remision, '' ) AS remision, IF( m.F_ConMov = 1, com.proveedor, '' ) AS proveedor, IFNULL(CASE m.F_ConMov WHEN 51 THEN fact.factura WHEN 3 THEN fact.factura WHEN 4 THEN dev.factura WHEN 5 THEN dev.factura ELSE m.F_DocMov END,'') AS folioSalida, IFNULL(CASE m.F_ConMov WHEN 51 THEN fact.unidad WHEN 3 THEN fact.unidad WHEN 4 THEN dev.unidad WHEN 5 THEN dev.unidad ELSE 'CEDIS CENTRAL' END,'')  AS puntoEntrega, c.F_DesCon AS concepto, m.F_ProMov AS clave, l.F_ClaLot AS lote, DATE_FORMAT( l.F_FecCad, '%d/%m/%Y' ) AS caducidad, (m.F_CantMov * m.F_SigMov ) AS cantidadMovimiento,    u.F_DesUbi AS ubicacion,     o.F_DesOri AS origen, p.F_DesProy AS proyecto, DATE_FORMAT( m.F_FecMov, '%d/%m/%Y' ) AS fechaMovimiento,    m.F_hora AS hora, IFNULL(CASE m.F_ConMov WHEN 1 THEN com.obcom WHEN 3 THEN 'Folio Cancelado' WHEN 4 THEN dev.coment WHEN 5 THEN dev.coment WHEN 51 THEN fact.Comen ELSE '' END,'') AS comentarios, IFNULL(CASE m.F_ConMov WHEN 3 THEN fact.factura WHEN 4 THEN m.F_DocMov WHEN 5 THEN m.F_DocMov ELSE '' END,'') AS folioReferencia, IFNULL(CASE m.F_ConMov WHEN 51 THEN DATE_FORMAT( fact.F_FecEnt, '%d/%m/%Y' ) ELSE '' END,'') AS fechaEnt FROM tb_movinv m  INNER JOIN tb_coninv c ON m.F_ConMov = c.F_IdCon INNER JOIN tb_ubica u ON m.F_UbiMov = u.F_ClaUbi INNER JOIN tb_lote l ON m.F_LotMov = l.F_FolLot INNER JOIN tb_medica mm ON mm.F_ClaPro = m.F_ProMov AND m.F_ProMov = l.F_ClaPro AND m.F_UbiMov = l.F_Ubica LEFT JOIN tb_proyectos p ON l.F_Proyecto = p.F_Id LEFT JOIN tb_origen o ON o.F_ClaOri = l.F_Origen"
//            + "LEFT JOIN (SELECT c.F_ClaDoc AS documento,c.F_OrdCom AS ori,c.F_FolRemi AS remision,c.F_Lote AS folLot,c.F_ClaPro AS clave, p.F_NomPro AS proveedor,c.F_Obser AS obcom FROM tb_compra c INNER JOIN tb_proveedor p ON p.F_ClaProve = c.F_ProVee WHERE c.F_FecApl = ? GROUP BY    c.F_ClaDoc,c.F_FolRemi,c.F_Lote) com ON com.documento = m.F_DocMov AND com.clave = m.F_ProMov AND com.folLot = m.F_LotMov"
//            + "LEFT JOIN (SELECT f.F_ClaDoc AS factura, f.F_Lote AS folLot, f.F_ClaPro AS clave, f.F_Proyecto AS proyecto, u.F_NomCli AS unidad, ob.F_Obser AS Comen, f.F_FecEnt FROM tb_factura f INNER JOIN tb_uniatn u ON u.F_ClaCli = f.F_ClaCli INNER JOIN tb_obserfact ob ON ob.F_IdFact = f.F_ClaDoc   GROUP BY f.F_ClaDoc, f.F_Proyecto, f.F_Lote) fact ON fact.factura = m.F_DocMov AND fact.clave = m.F_ProMov AND fact.folLot = m.F_LotMov"
//            + "LEFT JOIN (SELECT d.F_DocDev AS devolucion, d.F_DocRef AS factura, f.F_Lote AS folLot,    f.F_ClaPro AS clave, f.F_Proyecto AS proyecto, u.F_NomCli AS unidad, d.F_Obs AS coment FROM tb_factura f INNER JOIN tb_devoluciones d ON DATE( d.F_FecDev ) = ? AND f.F_ClaDoc = d.F_DocRef INNER JOIN tb_uniatn u ON u.F_ClaCli = f.F_ClaCli GROUP BY f.F_ClaDoc, d.F_IdDev, f.F_Proyecto, f.F_Lote) dev ON dev.devolucion = m.F_DocMov AND dev.clave = m.F_ProMov AND dev.folLot = m.F_LotMov WHERE m.F_FecMov = ? AND m.F_ConMov NOT IN ( 1000, 1001 ) GROUP BY m.F_IdMov ORDER BY m.F_IdMov;";

    public static final String OBTENER_KARDEX_REDISTRIBUCION_POR_FECHA = "SELECT m.F_User AS usuario, c.F_DesCon AS concepto, m.F_ProMov AS clave, l.F_ClaLot AS lote, DATE_FORMAT( l.F_FecCad, '%d/%m/%Y') AS caducidad,( m.F_CantMov * m.F_SigMov ) AS cantidad, m.F_CostMov AS costo, u.F_DesUbi AS ubicacion, DATE_FORMAT( m.F_FecMov, '%d/%m/%Y' ) AS fechaMovimiento, m.F_hora AS hora, m.F_DocMov AS documento, com.F_FolRemi AS remision, m.F_IdMov AS idMovimiento, l.F_Proyecto AS proyecto, p.F_DesProy AS descProyecto, o.F_DesOri AS origen, IFNULL(m.F_Comentarios,'') as comentarios FROM tb_movinv m INNER JOIN tb_coninv c ON m.F_ConMov = c.F_IdCon INNER JOIN tb_ubica u ON m.F_UbiMov = u.F_ClaUbi INNER JOIN tb_lote l ON m.F_LotMov = l.F_FolLot AND m.F_ProMov = l.F_ClaPro AND m.F_UbiMov = l.F_Ubica LEFT JOIN tb_compra com ON l.F_FolLot = com.F_Lote  LEFT JOIN tb_origen o ON o.F_ClaOri = l.F_Origen LEFT JOIN tb_proyectos p ON l.F_Proyecto = p.F_Id WHERE m.F_FecMov =? AND ( m.F_ConMov = 1000 OR m.F_ConMov = 1 OR m.F_ConMov = 1001) GROUP BY m.F_IdMov ORDER BY m.F_IdMov;";

//    public static final String OBTENER_KARDEX_POR_FECHA_EXPORTAR = "SELECT m.F_IdMov AS noMov, m.F_User AS usuario, mm.F_DesPro AS descripcion, IF( m.F_ConMov = 1, com.ori, '') AS ori, IF ( m.F_ConMov = 1, com.remision, '' ) AS remision, IF ( m.F_ConMov = 1, com.proveedor, '' ) AS proveedor, CASE m.F_ConMov WHEN 51 THEN fact.factura WHEN 3 THEN fact.factura WHEN 1 THEN '' ELSE IFNULL( dev.devolucion, '' ) END AS folioSalida, CASE m.F_ConMov WHEN 51 THEN fact.unidad WHEN 3 THEN fact.unidad WHEN 1 THEN '' ELSE IFNULL( dev.unidad, '' ) END AS puntoEntrega, c.F_DesCon AS concepto, m.F_ProMov AS clave, l.F_ClaLot AS lote, DATE_FORMAT( l.F_FecCad, '%d/%m/%Y' ) AS caducidad, ( m.F_CantMov * m.F_SigMov ) AS cantidadMovimiento, u.F_DesUbi AS ubicacion, p.F_DesProy AS proyecto, DATE_FORMAT( m.F_FecMov, '%d/%m/%Y' ) AS fechaMovimiento, m.F_hora AS hora,o.F_DesOri AS origen, IFNULL(m.F_Comentarios,'') as comentarios  FROM tb_movinv m INNER JOIN tb_coninv c ON m.F_ConMov = c.F_IdCon INNER JOIN tb_ubica u ON m.F_UbiMov = u.F_ClaUbi INNER JOIN tb_lote l ON m.F_LotMov = l.F_FolLot INNER JOIN tb_medica mm ON mm.F_ClaPro = m.F_ProMov AND m.F_ProMov = l.F_ClaPro AND m.F_UbiMov = l.F_Ubica LEFT JOIN tb_proyectos p ON l.F_Proyecto = p.F_Id   LEFT JOIN tb_origen o ON o.F_ClaOri = l.F_Origen LEFT JOIN ( SELECT c.F_ClaDoc AS documento, c.F_OrdCom AS ori, c.F_FolRemi AS remision, c.F_Lote AS folLot, c.F_ClaPro AS clave, p.F_NomPro AS proveedor FROM tb_compra c INNER JOIN tb_proveedor p ON p.F_ClaProve = c.F_ProVee WHERE c.F_FecApl = ? GROUP BY c.F_ClaDoc, c.F_FolRemi, c.F_Lote ) com ON com.documento = m.F_DocMov AND com.clave = m.F_ProMov AND com.folLot = m.F_LotMov LEFT JOIN ( SELECT f.F_ClaDoc AS factura, f.F_Lote AS folLot, f.F_ClaPro AS clave, f.F_Proyecto AS proyecto, u.F_NomCli AS unidad FROM tb_factura f INNER JOIN tb_uniatn u ON u.F_ClaCli = f.F_ClaCli AND f.F_FecApl = ? GROUP BY f.F_ClaDoc, f.F_Proyecto, f.F_Lote ) fact ON fact.factura = m.F_DocMov AND fact.clave = m.F_ProMov AND fact.folLot = m.F_LotMov LEFT JOIN ( SELECT d.F_DocDev AS devolucion, f.F_ClaDoc AS factura, f.F_Lote AS folLot, f.F_ClaPro AS clave, f.F_Proyecto AS proyecto, u.F_NomCli AS unidad FROM tb_factura f INNER JOIN tb_devoluciones d ON DATE( d.F_FecDev ) = ? AND f.F_ClaDoc = d.F_DocRef INNER JOIN tb_uniatn u ON u.F_ClaCli = f.F_ClaCli GROUP BY f.F_ClaDoc, f.F_Proyecto, f.F_Lote ) dev ON dev.devolucion = m.F_DocMov AND dev.clave = m.F_ProMov AND dev.folLot = m.F_LotMov WHERE m.F_FecMov = ? AND m.F_ConMov NOT IN (1000,1001) GROUP BY m.F_IdMov ORDER BY m.F_IdMov;";
    public static final String OBTENER_KARDEX_POR_FECHA_EXPORTAR = "SELECT m.F_IdMov AS noMov, m.F_User AS usuario,IF( m.F_ConMov = 1, com.ori, '' ) AS ori,IF( m.F_ConMov = 1, com.remision, '' ) AS remision, IF( m.F_ConMov = 1, com.proveedor, '' ) AS proveedor, IFNULL(CASE    m.F_ConMov WHEN 51 THEN    fact.factura WHEN 3 THEN fact.factura WHEN 4 THEN dev.factura WHEN 5 THEN dev.factura ELSE m.F_DocMov END,'') AS folioSalida, IFNULL(CASE m.F_ConMov WHEN 3 THEN fact.factura WHEN 4 THEN m.F_DocMov WHEN 5 THEN m.F_DocMov ELSE '' END,'') AS folioReferencia, IFNULL(CASE m.F_ConMov WHEN 51 THEN fact.unidad WHEN 3 THEN fact.unidad WHEN 4 THEN dev.unidad WHEN 5 THEN dev.unidad ELSE 'CEDIS CENTRAL' END,'') AS puntoEntrega, c.F_DesCon AS concepto,    m.F_ProMov AS clave,    l.F_ClaLot AS lote, SUBSTRING(mm.F_DesPro ,20) AS descripcion, DATE_FORMAT( l.F_FecCad, '%d/%m/%Y' ) AS caducidad,(m.F_CantMov * m.F_SigMov ) AS cantidadMovimiento, u.F_DesUbi AS ubicacion, o.F_DesOri AS origen, p.F_DesProy AS proyecto, DATE_FORMAT( m.F_FecMov, '%d/%m/%Y' ) AS fechaMovimiento, IFNULL(CASE m.F_ConMov WHEN 51 THEN DATE_FORMAT( fact.F_FecEnt, '%d/%m/%Y' ) ELSE '' END,'') AS fechaEnt, m.F_hora AS hora, IFNULL(CASE    m.F_ConMov WHEN 1 THEN    com.obcom     WHEN 3 THEN    'Folio Cancelado'     WHEN 4 THEN    dev.coment     WHEN 5 THEN    dev.coment     WHEN 51 THEN    fact.Comen ELSE '' END,'') AS comentarios, CASE WHEN com.ordSuministro = 'NULL' THEN  '' ELSE IFNULL(com.ordSuministro, '') END AS ordSuministro FROM tb_movinv m  "
            + "INNER JOIN tb_coninv c ON m.F_ConMov = c.F_IdCon "
            + "INNER JOIN tb_ubica u ON m.F_UbiMov = u.F_ClaUbi "
            + "INNER JOIN tb_lote l ON m.F_LotMov = l.F_FolLot "
            + "INNER JOIN tb_medica mm ON mm.F_ClaPro = m.F_ProMov AND m.F_ProMov = l.F_ClaPro AND m.F_UbiMov = l.F_Ubica "
            + "LEFT JOIN tb_proyectos p ON l.F_Proyecto = p.F_Id LEFT JOIN tb_origen o ON o.F_ClaOri = l.F_Origen "
            + "LEFT JOIN (SELECT c.F_ClaDoc AS documento,c.F_OrdCom AS ori,c.F_FolRemi AS remision,c.F_Lote AS folLot,c.F_ClaPro AS clave,    p.F_NomPro AS proveedor,c.F_Obser AS obcom, c.F_OrdenSuministro AS ordSuministro FROM    tb_compra c INNER JOIN tb_proveedor p ON p.F_ClaProve = c.F_ProVee WHERE c.F_FecApl = ? GROUP BY c.F_ClaDoc,c.F_FolRemi,c.F_Lote) com ON com.documento = m.F_DocMov AND com.clave = m.F_ProMov AND com.folLot = m.F_LotMov \n"
            + "LEFT JOIN (SELECT f.F_ClaDoc AS factura, f.F_Lote AS folLot, f.F_ClaPro AS clave, f.F_Proyecto AS proyecto, u.F_NomCli AS unidad, ob.F_Obser AS Comen,    f.F_FecEnt FROM    tb_factura f INNER JOIN tb_uniatn u ON u.F_ClaCli = f.F_ClaCli INNER JOIN tb_obserfact ob ON ob.F_IdFact = f.F_ClaDoc AND ob.F_Proyecto = f.F_Proyecto  GROUP BY f.F_ClaDoc, f.F_Proyecto, f.F_Lote) fact ON fact.factura = m.F_DocMov AND fact.clave = m.F_ProMov AND fact.folLot = m.F_LotMov \n"
            + "LEFT JOIN (SELECT d.F_DocDev AS devolucion, d.F_DocRef AS factura, f.F_Lote AS folLot,    f.F_ClaPro AS clave, f.F_Proyecto AS proyecto, u.F_NomCli AS unidad, d.F_Obs AS coment FROM tb_factura f INNER JOIN tb_devoluciones d ON DATE( d.F_FecDev ) = ? AND f.F_ClaDoc = d.F_DocRef INNER JOIN tb_uniatn u ON u.F_ClaCli = f.F_ClaCli GROUP BY    f.F_ClaDoc, d.F_IdDev, f.F_Proyecto, f.F_Lote) dev ON dev.devolucion = m.F_DocMov AND dev.clave = m.F_ProMov AND dev.folLot = m.F_LotMov WHERE    m.F_FecMov = ? AND m.F_ConMov NOT IN ( 1000, 1001 ) GROUP BY m.F_IdMov ORDER BY    m.F_IdMov; ";

}
